<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger. All Rights Reserved.
 * Contributor(s): Valmir C. Trindade - Translated to Brazilian Portuguese - 30/11/2013 - www.ttcasolucoes.com.br
 ************************************************************************************/

$languageStrings = Array (
	'MailManager' => 'Gestor Mensagens',
	
	// General translations
	'LBL_Folders'         => 'Pastas',
	'LBL_Newer'           => 'Recente',
	'LBL_Older'           => 'Antigo',
	'LBL_No_Mails_Found'  => 'Nenhuma mensagem encontrada.',
	'LBL_Go_Back'         => 'Retornar',
	'LBL_Reply_All'       => 'Responder a todos',
	'LBL_Reply'           => 'Responder',
	'LBL_Mark_As_Unread'  => 'Marcar como não lida',
	'LBL_Previous'        => 'anterior',
	'LBL_Next'            => 'próxima',
	'LBL_RELATED_RECORDS' => 'Registros Relacionados',
	'LBL_Mailbox'         => 'Caixa Entrada',
	'LBL_Outbox'          => 'Caixa Saída CRM',
	'LBL_Like'            => 'como',
	'LBL_Mail_Server'     => 'Nome Servidor Mensagem ou IP',
	'LBL_Refresh'         => 'Atualizar',
	'LBL_Cancel'          => 'Cancelar',
	'LBL_Send'            => 'Enviar',
	'LBL_Compose'         => 'Nova Mensagem',
	'LBL_Forward'         => 'Enviar Cópia',
	'LBL_Remove'          => 'Remover',
	'LBL_Associate'       => 'Associado',
	'LBL_Create_Contact'  => 'Criar Contato',
	'LBL_No_Matching_Record_Found' => 'Nenhum registro foi encontrado.',
	'LBL_ACTIONS'         => 'Ações',
	'LBL_Search'          => 'Pesquisar',
	'LBL_Delete'            =>  'Apagar',
	
	'LBL_Username'             => 'Nome Usuário',
	'LBL_Your_Mailbox_Account' => 'sua conta de correio',
	'LBL_Password'             => 'Senha',
	'LBL_Account_Password'     => 'senha conta',
	'LBL_Protocol'    => 'Protocolo',
	'LBL_Imap2'       => 'IMAP2',
	'LBL_Imap4'       => 'IMAP4',
	'LBL_SSL_Options' => 'Opções SSL',
	'LBL_No_TLS'      => 'Sem TLS',
	'LBL_TLS'         => 'TLS',
	'LBL_SSL'         => 'SSL',
	'LBL_Certificate_Validations' => 'Validações Certificado',
	'LBL_Validate_Cert'           => 'Validar cert',
	'LBL_Do_Not_Validate_Cert'    => 'Não validar cert',
	'LBL_SELECT_ACCOUNT_TYPE'     => 'Selecionar Provedor',
	
	'LBL_FROM'        => 'De',
	'LBL_TO'          => 'Para',
	'LBL_CC'          => 'Cc',
	'LBL_BCC'         => 'Bcc',
	'LBL_Date'        => 'Data',
	'LBL_Attachments' => 'Anexos',
	'LBL_EMAIL_TEMPLATES_LIST'=>'Modelos Emails',
	'LBL_SELECT_EMAIL_TEMPLATE'=>'Selecionar Modelo Email',
	'LBL_ATTACHMENTS'  =>'Anexo:',
	'LBL_SELECT_DOCUMENTS'=>'Selecionar Documentos',
	'LBL_IN' =>'em',
	'LBL_FIND'=>'Localizar',
	'LBL_SAVE_NOW'=>'Salvar Agora',
	'LBL_Drafts'=>'Rascunhos',
 	'LBL_NO_EMAILS_SELECTED' => 'Nenhum Email Selecionado.',
	'LBL_SUBJECT'	=>	'Assunto',
	'LBL_WRITE_ACCESS_FOR'	=>'Acesso escrita para',
	'LBL_READ_ACCESS_FOR'	=>'Acesso leitura para',
	'LBL_MODULE_DENIED' => 'modulo negado!',
	'LBL_REFRESH_TIME'=>'Tempo Atualização',
	'LBL_NONE' => 'Nada',
	'LBL_5_MIN' => '5 Minutos',
	'LBL_10_MIN' => '10 Minutes',
	'LBL_MOVE_TO'=>'Mover Para...',
    'LBL_MAILMANAGER_ADD_Contacts' => 'Adicionar Contato',
    'LBL_MAILMANAGER_ADD_Accounts' => 'Adicionar Organização',
    'LBL_MAILMANAGER_ADD_Leads' => 'Adicionar Lead',
    'LBL_MAILMANAGER_ADD_Calendar' => 'Adicionar Compromisso',
    'LBL_MAILMANAGER_ADD_HelpDesk' => 'Adicionar Chamado',
    'LBL_MAILMANAGER_ADD_Emails' => 'Adicionar Email',
    'LBL_MAILMANAGER_ADD_ModComments' => 'Adicionar Comentário',
    'LBL_ADD' => 'Adicionar',
	'JSLBL_Body_Cannot_Be_Empty' => 'O corpo da mensagem não pode estar vazio',
	'LBL_ALLMAILS' => 'Todas as Mensagens',
	'LBL_TO_CONTACTS' => 'Para Contatos',
	'LBL_TO_ACCOUNTS' => 'Para Organizações',
	'LBL_TO_LEADS' => 'Para Leads',
	'LBL_TO_USERS' => 'Para Usuários',
	'LBL_SENT_MAILS' => 'Enviar Mensagens',
	'LBL_Print' => 'Imprimir',
	
	'LBL_SAVE_BUTTON_LABEL' => 'Salvar',
	'LBL_CANCEL_BUTTON_LABEL' => 'Cancelar',
	'LBL_CREATE_MAILBOX' => 'Criar Caixa Entrada',
	'LBL_WRITE_YOUR_COMMENT_HERE' => 'Adicionar seu comentário aqui ...',

);

$jsLanguageStrings = Array (
	'MailManager' => 'Gestor Mensagens',
	
	// Translations for JS (please use the prefix JSLBL in key)
	'JSLBL_Loading_Please_Wait'  => 'Carregando... por favor, aguarde',
	'JSLBL_Loading'              => 'Carregando',
	'JSLBL_Settings'             => 'Configurações',
	'JSLBL_Opening'              => 'Abrindo',
	'JSLBL_Deleting'              => 'Apagando',  
	'JSLBL_Updating'             => 'Atualizando',
	'JSLBL_Associating'          => 'Associando',
	'JSLBL_Saving_And_Verifying' => 'Salvando & Verificando',
	'JSLBL_Failed_To_Open_Mail'  => 'Falha ao abrir a mensagem',
	'JSLBL_Finding_Relation'     => 'Encontrando relação',
	'JSLBL_Find_Relation_Now'    => 'Encontrar relação agora',
	'JSLBL_Searching'            => 'Pesquisando',
	'JSLBL_Searching_Please_Wait'=> 'Pesquisando... por favor, aguarde',
	'JSLBL_Sending'              => 'Enviando',
	'JSLBL_Replied'              => 'Respondido',
	'JSLBL_Failed_To_Send_Mail'  => 'Falha ao enviar a mensagem',
	'JSLBL_Recepient_Cannot_Be_Empty' => 'Destinatário (Para) não pode estar vazio',
	'JSLBL_Subject_Cannot_Be_Empty'     => 'O Assunto não pode estar vazio',
	'JSLBL_Removing'                  => 'Removendo',
	'JSLBL_Choose_Server_Type'        => 'Escolha o tipo de servidor',
	'JSLBL_Other'                     => 'Outro',
	'JSLBL_Gmail'                     => 'Gmail',
	'JSLBL_Fastmail'                  => 'Fastmail',
	'JSLBL_Search_For_Email'          => 'Pesquisar email',
	'JSLBL_Nothing_Found'             => 'Nada encontrado',
	'JSLBL_Delete_Confirm'            =>'Deseja apagar os Emails de forma permanente?',
	'JSLBL_Delete_Mails_Confirm'      =>'Deseja apagar os Emails?',
	'JSLBL_Receipents_Warning_Message'=>'Por favor, selecione os destinatários',
	'JSLBL_NO_MATCH'				  => 'Nada encontrado',
	'JSLBL_Saving'					=> 'Salvando',
	'JSLBL_Failed_To_Save_Mail'		=>	'Falha ao salvar a mensagem',
	'JSLBL_ATTACHMENT_NOT_DELETED'	=>	'O anexo não pode ser apagado',
	'JSLBL_UPLOAD_CANCEL'	=> 'Cancelar',
	'JSLBL_UPLOAD_DROPFILES'=>'Solte os aquivos aqui para transferir',
	'JSLBL_UPLOAD_FILE'=>'Transferir',
	'JSLBL_UPLOAD_DELETE'=>'[x]',
	'JSLBL_UPLOAD_FAILED'=>'Falhou',
	'JSLBL_FILEUPLOAD_LIMIT_EXCEEDED'=>'O tamanho do arquivo excedeu o limite para transferência!!',
	'JSLBL_MAIL_SENT'=>'Mensagem Enviada',
	'JSLBL_EMAIL_FORMAT_INCORRECT'=>'Por favor, forneça endereço de email correto',
	'JSLBL_Saving'=>'Salvando',
	'JSLBL_SaveWith_EmptySubject'=>'Salvar com assunto vazio?',
	'JSLBL_Delete'            =>  'Apagar',
	'JSLBL_Drafts'=>'Rascunhos',
	'JSLBL_PASSWORD_CANNOT_BE_EMPTY'=>'A Senha não pode estar vazia',
	'JSLBL_SERVERNAME_CANNOT_BE_EMPTY'=>'O nome do Servidor não pode estar vazio',
	'JSLBL_USERNAME_CANNOT_BE_EMPTY'=>'O nome do Usuário não pode estar vazio',
	'JSLBL_ACCOUNTNAME_CANNOT_EMPTY'=>'O nome da Organização não pode estar vazio',
	'JSLBL_FROM'=>'De:',
	'JSLBL_DATE'=>'Data: ',
	'JSLBL_SUBJECT'=>'Assunto: ',
	'JSLBL_TO'=>'Para: ',
	'JSLBL_CC'=>'Cc: ',
	'JSLBL_FORWARD_MESSAGE_TEXT'=>'---------- Mensagem enviada ----------',
	'JSLBL_PLEASE_SELECT_ATLEAST_ONE_MAIL'=>'Por favor, selecione pelo menos uma mensagem',
	'JSLBL_PLEASE_SELECT_ATLEAST_ONE_RECORD'=>'Por favor, selecione pelo menos um registro',
	'JSLBL_MAIL_MOVED'=>'Mensagem(s) movida(s)',
	'JSLBL_MOVING'=>'Movendo Mensagem(s)',
	'JSLBL_LOADING_FOLDERS' => 'Carregando Pastas...',
	'JSLBL_ADD_COMMENT'=>'Adicionar Comentários',
    'JSLBL_Yahoo'=>'Yahoo',
    'JSLBL_CANNOT_ADD_EMPTY_COMMENT' => 'O Comentário não pode estar vazio',
    'JSLBL_NO_EMAILS_SELECTED' => 'Nenhum Email Selecionado.',
    'JSLBL_ENTER_SOME_VALUE' => 'Digite uma palavra para pesquisa',
    'JSLBL_DRAFT_MAIL_SAVED'=>'A mensagem foi salva nos Rascunhos',
);

// Special Handling: Mix of language strings are used.
$languageStrings = array_merge($languageStrings, $jsLanguageStrings);
