<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger. All Rights Reserved.
 * Contributor(s): Valmir C. Trindade - Translate to Brazilian Portuguese - 14/07/2013 - www.ttcasolucoes.com.br
 ************************************************************************************/
$languageStrings = array(

	// Footer
	'APPTITLE' => 'vtiger CRM',
	'POWEREDBY'=> 'Suportado por vtiger CRM' ,
	'LBL_READ_LICENSE' => 'Ler a Licença',
	'LBL_PRIVACY_POLICY' => 'Política de Privacidade',

	// Common Actions
	'LBL_SELECT_ALL' => 'Selecionar Tudo' ,
	'LBL_SELECT_TO_LOAD_LIST' => 'Selecione Carregar Lista',
	'LBL_CREATING_NEW' => 'Nova Criação',
	'LBL_EDITING'=> 'Editando', 
	'LBL_SAVE' => 'Salvar',
	'LBL_CANCEL' => 'Cancelar',
	'LBL_BACK' => 'Voltar', 
	'LBL_IMPORT' => 'Importar', 
	'LBL_EXPORT' => 'Exportar', 
	'LBL_FIND_DUPLICATES'=> 'Localizar Duplicados', 
	'LBL_MORE' => 'Mais', 
	'LBL_ACTIONS'=> 'Ações' , 
	'LBL_ADD'=> 'Adicionar' ,
	'LBL_EDIT' => 'Editar', 
	'LBL_DELETE' => 'Apagar', 
	'LBL_SETTINGS' => 'Configurações' , 
	'LBL_ADD_COMMENT'=> 'Adicionar Comentário' ,
	'LBL_EDIT_FIELDS'=> 'Editar Campos' ,
	'LBL_EDIT_WORKFLOWS' => 'Editar Workflows',
	'LBL_EDIT_PICKLIST_VALUES' => 'Editar Valores Lista Opções',
	'LBL_EDIT_MAILSCANNER' => 'Converter Emails',
	'LBL_RECORD_DELETE'=> 'O registro que você está tentando visualizar foi apagado.', 
	'LBL_RECORD_NOT_FOUND' => 'Os registros que você está tentando acessar não foram econtrados', 
	'LBL_EDIT_REASON' => 'Editar razão',

	//'LBL_EDIT_CURRENT_FILTER' => 'Edit Current Filter',
	//'LBL_DELETE_CURRENT_FILTER' => 'Delete Current Filter',
	'LBL_SELECT' => 'Selecionar', 
	'LBL_CLEAR'=> 'Limpar', 
	'LBL_YES'=> 'Sim' , 
	'LBL_NO' => 'Nenhum(a)' ,
	'LBL_SHOW_COMPLETE_DETAILS' => 'Detalhes Completos', 
	'LBL_MASS_EDITING' => 'Editar em Massa',
	'LBL_DESELECT_ALL_RECORDS' => 'Remover Seleção Todos Registros',
	'LBL_QUICK_CREATE' => 'Criar Rápido' , 
	'LBL_SEND_EMAIL' => 'Enviar Email',
	//SEND EMAIL translations
	'LBL_ALL_EMAILS' => 'Todas Contas email',
	'LBL_MUTIPLE_EMAIL_SELECT_ONE' => 'Este registro armazena múltiplas contas de email. Por favor, selecione as contas para as quais os emails deverão ser enviados',
	//SEND EMAIL translations
	'LBL_GO_TO_FULL_FORM'=> 'Forma Completa' ,
	'LBL_SEND_SMS' => 'Enviar SMS',
	'LBL_FOUND'=> 'Encontrado(a)' , 
	'LBL_CLICK_ADD'=> 'Clique adicionar' ,
	'LBL_ADD_MORE_FIELDS'=> 'Adicionar mais campos' ,
	'LBL_ADD_NOTE' => 'Adicionar Nota', 
	'LBL_CREATE_NEW' => 'Criar Novo',
	'LBL_ADD_EVENT'=> 'Adicionar Evento' ,
	'LBL_ADD_TASK' => 'Adicionar Tarefa',
	'LBL_MARKETING_AND_SALES'=> 'MARKETING & VENDAS' ,
	'LBL_TOOLS_HEADER' => 'FERRAMENTAS' ,
	'LBL_SUPPORT'=> 'SUPORTE' ,
	'LBL_INVENTORY'=> 'ESTOQUE' ,
	'LBL_ANALYTICS'=> 'ANALÍTICOS' ,
	'LBL_HOME' => 'Principal', 

	// Common Link Labels
	'LBL_LAST_VIEWED_RECORDS'=> 'Últimos Registros Visualizados' ,
	'LBL_DASHBOARD'=> 'Painel', 
	'LBL_USER_SETTINGS'=> 'Configurações Usuários' ,
	'LBL_MY_PREFERENCES' => 'Minhas Preferências', 
	'LBL_SIGN_OUT' => 'Desconectar' ,
	'LBL_HELP' => 'Ajuda' ,
	'LBL_DOCUMENTATION' => 'Documentação',
	'LBL_VIDEO_TUTORIAL' => 'Tutorial Vídeo',
	'LBL_FEEDBACK' => 'Feedback', 
	'LBL_CRM_SETTINGS' => 'Configurações CRM' ,
	'LBL_ON_DEMAND_ADMIN' => 'Adicionar / Excluir Usuários',
	'LBL_ANNOUNCEMENT' => 'Anúncios',
	'LBL_CALENDAR' => 'Agenda',
	'LBL_POST' => 'Postar',
	'LBL_GUIDER' => 'Guia',
	'LBL_DISPLAY_TYPE' => 'Mostrar Tipo',
	'LBL_DISPLAY_WIDETYPE' => 'Largo',
	'LBL_DISPLAY_MEDIUMTYPE' => 'Médio',
	'LBL_DISPLAY_NARROWTYPE' => 'Estreito',
	'LBL_TAG_THIS_RECORD' => 'Etiquetar este Registro',
	'LBL_PAGE' => 'Página',
	'LBL_LISTVIEW_PAGE_JUMP' => 'Ir para Página',
	'LBL_PROFILE_PASSWORD' => 'Perfil / Senha',

	// Common Fields
	'LBL_USER' => 'Usuário',
	'LBL_GROUP' => 'Grupo',
	'Last Modified By' => 'Última Modificação por',
	'Created Time' => 'Data Criação', 
	'Modified Time'=> 'Hora Modificação', 
	'Description'=> 'Descrição' , 
	'Assigned To'=> 'Responsável',

	//Loading Labels
	'LBL_LOADING'=> 'Carregando...' , 
	'LBL_LOADING_WIDGET' => 'Carregando Widget',
	'LBL_LOADING_LISTVIEW_CONTENTS' => 'Carregando ... por favor, aguarde.' ,

	// Detail View
	'LBL_UPDATES'=> 'Atualizações' ,
	'LBL_SHOW_FULL_DETAILS' => 'Exibir Detalhes Completos',
	'LBL_SUMMARY_DETAILS'=> 'Detalhes Resumido' ,
	'LBL_ADD_NEW_COMMENT'=> 'Adicionar Novo Comentário' ,
	'LBL_NO_UPDATES' => 'Nenhuma Atualização',
	'LBL_ACTIVITIES' => 'Atividades',
	'LBL_NO_PENDING_ACTIVITIES' => 'Nenhuma atividade pendente',
	'LBL_SUMMARY' => 'Resumo',
	'LBL_DETAILS' => 'Detalhes',

	// Popup window
	'LBL_SEARCH_FOR' => 'Pesquisar por' , 
	'LBL_IN' => 'Em', 
	'LBL_TYPE_SEARCH'=> 'Digite para pesquisar',
	'LBL_SEARCH_BUTTON'=> 'Botão Pesquisa' ,
	'LBL_ADVANCE_SEARCH' => 'Avançada',
	'LBL_LOADING_PLEASE_WAIT'=> 'Carregando, por favor, aguarde.' ,
	'LBL_PLEASE_SELECT_MODULE' => 'Por favor, selecione o módulo',

	//DropDown Category
	'LBL_USERS'=> 'Usuários' ,
	'LBL_GROUPS' => 'Grupos',

	//EditView Form Links
	'LBL_FULL_FORM'=> 'Forma Completa' ,
	'LBL_SIMPLE_FORM'=> 'Forma Simples' ,

	//Recent Comments
	'LBL_ADD_YOUR_COMMENT_HERE'=> 'Adicionar seu comentário aqui...',
	'LBL_REASON_FOR_CHANGING_COMMENT' => 'Motivo para mudar o comentário',
	'LBL_REPLY'=> 'Responder' ,
	'LBL_VIEW_THREAD'=> 'Visualizar Tópico' ,
	'LBL_NO_COMMENTS'=> 'Sem Comentários' ,
	'LBL_REPLIES'=> 'respostas' ,

	//Translation for all modules
	'Accounts' => 'Organizações', 
	'Assets' => 'Ativos',
	'Calendar' => 'Agenda', 
	'Campaigns'=> 'Campanhas' , 
	'Contacts' => 'Contatos', 
	'Documents'=> 'Documentos', 
	'Leads'=> 'Leads' , 
	'ModComments'=> 'Comentários',
	'Potentials' => 'Oportunidades', 
	'PriceBooks' => 'Listas Preços', 
	'Products' => 'Produtos' , 
	'Project'=> 'Projetos',
	'ProjectMilestone' => 'Milestones Projeto',
	'ProjectTask'=> 'Tarefas Projeto' ,
	'ServiceContracts' => 'Contratos Serviço', 
	'Services' => 'Serviços' , 
	'Vendors'=> 'Fornecedores', 
	'Rss'=> 'RSS' , 
	'Quotes' => 'Cotações', 
	'PurchaseOrder'=> 'Pedidos Compra' , 
	'SalesOrder' => 'Pedidos Venda', 
	'Invoice'=> 'Faturas',
	'MailManager' => 'Gestor Mensagens',
	'Activities' => 'Atividades',


	//Basic String Translation
	'LBL_ADD_RECORD' => 'Adicionar Registro',
	'LBL_RECENTLY_MODIFIED'=> 'Últimas Alterações' ,
	'LBL_RECORDS_LIST' => 'Lista Registros',
	'LBL_RECORD_SUMMARY' => 'Resumo Módulo',
	'LBL_RECORD_DETAILS' => 'Detalhes Módulo', // String original: 'LBL_RECORD_SUMMARY'=> 'Module Details',
	'LBL_ACCESS_DENIED_FOR'=> 'Acesso Negado para' ,
	'LBL_GO_BACK'=> 'Voltar', 
	'LBL_NO_DATA_AVAILABLE'=> 'Nenhum dado disponível' ,

	// Global Search
	'LBL_GLOBAL_SEARCH'=> 'Digite palavra chave e pressione Enter',
	'LBL_ALL_RECORDS' => 'Todos os Registros',
	'LBL_NO_RECORDS_FOUND' => 'Nenhum registro encontrado',

	//Filters & Advance Filter
	'LBL_AND'=> 'e' ,
	'LBL_OR' => 'ou', 
	'LBL_NONE' => '--Nada--', 
	'LBL_APPROVE'=> 'Aprovar' ,
	'LBL_DENY' => 'Negar',
	'LBL_EQUALS' => 'iguais',
	'LBL_NOT_EQUAL_TO' => 'não igual a',
	'LBL_STARTS_WITH'=> 'iniciar com' ,
	'LBL_ENDS_WITH'=> 'termina com' ,
	'LBL_CONTAINS' => 'contém',
	'LBL_DOES_NOT_CONTAIN' => 'não contém' ,
	'LBL_LESS_THAN'=> 'menor que' ,
	'LBL_GREATER_THAN' => 'maior que' ,
	'LBL_LESS_THAN_OR_EQUAL' => 'menor ou igual',
	'LBL_GREATER_OR_EQUAL' => 'maior ou igual',
	'LBL_BEFORE' => 'antes',
	'LBL_AFTER'=> 'depois' ,
	'LBL_BETWEEN'=> 'entre' ,
	'LBL_SEARCH' => 'Pesquisar' , 
	'LBL_SEARCH_IN'=> 'Pesquisar em' ,
	'LBL_ADD_CONDITION'=> 'Adicionar Condição' ,
	'LBL_ADD_GROUP'=> 'Adicionar Grupo' ,
	'LBL_FILTER_CONDITIONS'=> 'Condições de Filtro' ,
	'LBL_ALL_CONDITIONS' => 'Todas as Condições',
	'LBL_ALL_CONDITIONS_DESC'=> 'Todas as condições devem ser satisfeitas',
	'LBL_ANY_CONDITIONS' => 'Quaisquer Condições',
	'LBL_ANY_CONDITIONS_DESC'=> 'Ao menos uma das condições deve ser satisfeita',
	'LBL_SELECT_FIELD' => 'Selecionar Campo',
	'LBL_SELECT_MODULE'=> 'Selecionar Módulo' ,
	'LBL_CREATE_NEW_FILTER'=> 'Criar Novo Filtro' ,
	'All'=> 'Todos' ,
	'Others' => 'Outros',
	'Pending'=> 'Pendente',
	'Public' => 'Público',

	//Advance Search
	'LBL_SAVE_FILTER'=> 'Salvar Filtro' ,
	'LBL_SAVE_MODIFY_FILTER' => 'Salvar/Modicar Filtro',
	'LBL_SEARCH_RESULTS' => 'Resultados Pesquisa',
	'LBL_SAVE_AS_FILTER' => 'Salvar como Filtro',

	//Exception String Translation
	'LBL_NOT_ACCESSIBLE' => 'Não Acessivel',

	//Line Items
	'LBL_ITEM_DETAILS' => 'Detalhes do Item', 
	'LBL_CURRENCY' => 'Moeda' , 
	'LBL_TAX_MODE' => 'Tributação', 
	'LBL_INDIVIDUAL' => 'Individual', 
	'LBL_GROUP' => 'Grupo',
	'LBL_TOOLS'=> 'Ferramentas' , 
	'LBL_ITEM_NAME'=> 'Nome do Item', 
	'LBL_QTY_IN_STOCK' => 'Estoque', 
	'LBL_QTY'=> 'Quantidade' , 
	'LBL_LIST_PRICE' => 'Lista de Preço' , 
	'LBL_TOTAL'=> 'Total' , 
	'LBL_NET_PRICE'=> 'Preço Líquido' , 
	'LBL_DISCOUNT' => 'Desconto', 
	'LBL_TOTAL_AFTER_DISCOUNT' => 'Total após Desconto', 
	'LBL_TAX'=> 'Imposto' , 
	'LBL_ADD_PRODUCT'=> 'Adicionar Produto' , 
	'LBL_ADD_SERVICE'=> 'Adicionar Serviço',
	'LBL_ITEMS_TOTAL' => 'Items Total',
	'LBL_SHIPPING_AND_HANDLING_CHARGES' => 'Frete' ,
	'LBL_PRE_TAX_TOTAL' => 'Total Antes Imposto',
	'LBL_TAX_FOR_SHIPPING_AND_HANDLING' => 'Impostos s/ Frete' , 
	'LBL_SET_SHIPPING_AND_HANDLING_TAXES_FOR' => 'Definir Imposto Frete para' ,
	'LBL_ADJUSTMENT' => 'Ajuste', 
	'LBL_DEDUCT' => 'Deduzir' , 
	'LBL_GRAND_TOTAL'=> 'Total Geral' , 
	'LBL_ZERO_DISCOUNT'=> 'Sem Desconto', 
	'LBL_OF_PRICE' => 'de Preço' , 
	'LBL_DIRECT_PRICE_REDUCTION' => 'Redução Direta Preço' , 
	'LBL_SET_DISCOUNT_FOR' => 'Definir Disconto para',
	'LBL_STOCK_NOT_ENOUGH' => 'Estoque insuficiente',
	'LBL_MAX_QTY_SELECT' => 'Valor máximo é' ,
	'LBL_DRAG' => 'Arrastar',
	'LBL_TOTAL_TAX_AMOUNT' => 'Total Imposto' , 
	'LBL_DIRECT_AMOUNT_DISCOUNT' => 'Total Desconto Direto' , 
	'LBL_FINAL_DISCOUNT_AMOUNT'=> 'Soma Final Desconto' , 
	'LBL_MORE_CURRENCIES'=> 'outras moedas' ,
	'LBL_SET_TAX_FOR' => 'Definir Imposto para',
	'LBL_GROUP_TAX' => 'Grupo Imposto',
	'LBL_BILLING_ADDRESS_FROM' => 'Copiar Endereço Faturamento de',
	'LBL_SHIPPING_ADDRESS_FROM' => 'Copiar Endereço Entrega de',
	'LBL_COPY_SHIPPING_ADDRESS' => 'Endereço Entrega',
	'LBL_COPY_BILLING_ADDRESS' => 'Endereço Faturamento',

	//DetailView Actions 
	'LBL_CREATE' => 'Criar' , 
	'LBL_GENERATE' => 'Gerar' , 
	'LBL_DUPLICATE'=> 'Duplicar',
	'Add Note' => 'Adicionar Documento',

	//Dashboard String
	'LBL_ADD_WIDGET' => 'Adicionar Widget',
	'LBL_COMMENTS' => 'Comentários', 
	'LBL_REFRESH'=> 'Atualizar' , 
	'LBL_CLOSE'=> 'Fechar', 
	'LBL_ALL'=> 'Todos' , 
	'LBL_UPDATED'=> 'Atualizado', 
	'LBL_FROM' => 'de',
	'LBL_TO' => 'para',
	'LBL_to' => 'para',
	'LBL_ON' => 'em',
	'LBL_OF' => 'de',
	'LBL_BY' => 'Por ', 
	'LBL_ADDED'=> 'adicionado' ,
	'LBL_FOR'=> 'para', 
	'LBL_CREATED'=> 'Criado', 
	'LBL_DELETED'=> 'apagado' ,
	'LBL_RESTORED' => 'restaurado',
	'LBL_COMMENTED'=> 'comentado' ,
	'LBL_REMOVED'=> 'removido' ,
	'LBL_REMOVE' => 'Remover',
	'LBL_AT' => 'em',
	'LBL_MINE' => 'Minha(s)',
	'History'=> 'Histórico',
	'Upcoming Tasks' => 'Próximas Tarefas',
	'LBL_YEAR' => 'ano',
	'LBL_YEARS'=> 'anos' ,
	'LBL_MONTH'=> 'mês' ,
	'LBL_MONTHS' => 'meses',
	'LBL_DAY'=> 'dia' ,
	'LBL_DAYS' => 'dias',
	'LBL_HOUR' => 'hora',
	'LBL_HOURS'=> 'horas' ,
	'LBL_MINUTE' => 'minuto',
	'LBL_MINUTES'=> 'Minutos' ,
	'LBL_SECOND' => 'segundo',
	'LBL_SECONDS'=> 'segundos' ,
	'LBL_JUSTNOW'=> 'agora',
	'LBL_CUSTOM_INFORMATION' => 'Informação Customizada', 
	'LBL_NO_RECENT_UPDATES'=> 'Nenhuma atualização recente' ,
	'LBL_NO_DATA'=> 'Nenhum dado',
	'LBL_PERMISSION_DENIED'=> 'Permissão negada' ,
	'LBL_HANDLER_NOT_FOUND'=> 'Nenhum Almoxarife encontrado' ,
	'LBL_FILTER' => 'Filtro',
	'LBL_DUE'=> 'vencido em' ,
	'LBL_DAYS' => 'dias',
	'LBL_COMPLETED'=> 'concluído' ,
	'LBL_AGO'=> 'atrás' ,
	'LBL_CHANGED'=> 'alterado' ,
	'Single_Users' => 'Usuário',
	'LBL_MATCHED_THIS_CRITERIA'=> 'corresponde a este critério' ,
	'LBL_NO_SCHEDULED_ACTIVITIES'=> 'Nenhuma atividade agendada' ,
	'LBL_NO_OVERDUE_ACTIVITIES'=> 'Nenhuma atividade atrasada' ,
	'LBL_NO_UPDATES_OR_COMMENTS' => 'Nenhuma atualização ou comentário',
	'LBL_MINI_LIST' => 'Mini Lista',
	'LBL_NOTEPAD' => 'Bloco de Notas',
	'LBL_NOTEPAD_NAME' => 'Nome Bloco Notas',
	'LBL_NOTEPAD_CONTENT' => 'Conteúdo Bloco Notas',
	'LBL_LAST_SAVED_ON' => 'Última salvo em',
	'Mini List' => 'Mini Lista',
	'Notebook' => 'Bloco de Notas',
	'LBL_RESULT_FOR_THE_TAG' => 'Resultados para etiqueta',

	// Basic Strings- custom view
	'LBL_VIEW_NAME'=> 'Visualizar Nome' ,
	'LBL_CREATE_VIEW'=> 'Criação nova Visualização' ,
	'LBL_BASIC_DETAILS'=> 'Detalhes Básicos' ,
	'LBL_CHOOSE_COLUMNS' => 'Escolha as Colunas e Ordem',
	'LBL_MAX_NUMBER_FILTER_COLUMNS' => 'Máx 7' ,
	'LBL_FILTER_ON_DATE' => 'Filtrar data',
	'LBL_CHOOSE_FILTER_CONDITIONS' => 'Escolha as Condições do Filtro',
	'LBL_ADD_CONDITION' => 'Adicionar Condição',
	'LBL_SET_AS_DEFAULT' => 'Definir como Padrão',
	'LBL_LIST_IN_METRICS'=> 'Listar em Métricas' ,
	'LBL_SET_AS_PUBLIC'=> 'Definir como Público',
	'LBL_AND' => 'e',
	'LBL_OR' => 'ou',
	'LBL_ADD_MORE_COLUMNS' => 'Adicionar mais Colunas',
	'LBL_ADD_GROUP' => 'Adicionar Grupo',


	//DateFilter Conditions
	'LBL_CUSTOM' => 'Customização',
	'LBL_PREVIOUS_FY'=> 'Ano Anterior' ,
	'LBL_CURRENT_FY' => 'Ano Atual',
	'LBL_NEXT_FY'=> 'Próximo Ano' ,
	'LBL_PREVIOUS_FQ'=> 'Semestre Anterior' ,
	'LBL_CURRENT_FQ' => 'Semestre Atual',
	'LBL_NEXT_FQ'=> 'Próximo Semestre' ,
	'LBL_YESTERDAY' => 'Ontem',
	'LBL_TODAY' => 'Hoje',
	'LBL_TOMORROW' => 'Amanhã',
	'LBL_LAST_WEEK'=> 'Última Semana',
	'LBL_CURRENT_WEEK' => 'Semana Atual',
	'LBL_NEXT_WEEK'=> 'Próxima Semana' ,
	'LBL_LAST_MONTH' => 'Último Mês',
	'LBL_CURRENT_MONTH'=> 'Mês Atual' ,
	'LBL_NEXT_MONTH' => 'Próximo Mês',
	'LBL_LAST_7_DAYS'=> 'Últimos 7 Dias' ,
	'LBL_LAST_30_DAYS' => 'Últimos 30 Dias',
	'LBL_LAST_60_DAYS' => 'Últimos 60 Dias',
	'LBL_LAST_90_DAYS' => 'Últimos 90 Dias',
	'LBL_LAST_120_DAYS'=> 'Últimos 120 Dias' ,
	'LBL_NEXT_30_DAYS' => 'Próximos 30 Dias',
	'LBL_NEXT_60_DAYS' => 'Próximos 60 Dias',
	'LBL_NEXT_90_DAYS' => 'Próximos 90 Dias',
	'LBL_NEXT_120_DAYS'=> 'Próximos 120 Dias' ,

	//advanced Filter Options
	'LBL_NONE' => 'NADA',
	'LBL_EQUALS' => 'igual',
	'LBL_NOT_EQUAL_TO' => 'diferente',
	'LBL_STARTS_WITH' => 'inicia com',
	'LBL_ENDS_WITH' => 'final com',
	'LBL_CONTAINS' => 'contém',
	'LBL_DOES_NOT_CONTAIN' => 'não contém',
	'LBL_LESS_THAN' => 'menor que',
	'LBL_GREATER_THAN' => 'maior que',
	'LBL_LESS_THAN_OR_EQUAL' => 'menor ou igual',
	'LBL_GREATER_OR_EQUAL' => 'maior ou igual',
	'LBL_BEFORE' => 'antes',
	'LBL_AFTER' => 'depois',
	'LBL_BETWEEN' => 'entre',
	'LBL_IS_EMPTY'=> 'vazio',

	//Detail view summary widgets
	'LBL_OWNER'=> 'Proprietário' ,
	'LBL_CREATED_ON' => 'Criado em',
	'LBL_MODIFIED_ON'=> 'Modificado em' ,
	'LBL_MODIFIED' => 'Modificado',
	'LBL_COMMENTED' => 'Comentado',

    //calender set-reminder
	'LBL_BEFORE_EVENT' => 'Evento Anterior' ,

	//Dashboard widgets
	'History' => 'Histórico',
	'Upcoming Activities'=> 'Próximas Atividades',
	'Overdue Activities' => 'Atividades Atrasadas',
	'Funnel' => 'Funil',
	'Potentials by Stage'=> 'Oportunidades por Estágio',
	'Pipelined Amount' => 'Funil de Vendas',
	'Total Revenue'=> 'Receita Total' ,
	'Top Potentials' => 'Principais Oportunidades',
	'Forecast' => 'Previsão',
	'Leads Created'=> 'Leads Criados' ,
	'Leads by Status'=> 'Leads por Status' ,
	'Leads by Source'=> 'Leads por Fonte' ,
	'Leads by Industry'=> 'Leads por Atividade' ,
	'Tickets by Status' => 'Tickets por Status',
	'Open Tickets' => 'Tickets Abertos',
	'Funnel Amount' => 'Valor Total por Estágio de Vendas',

	//Exports strings
	'LBL_EXPORT_ALL_DATA'=> 'Exportar todos os dados' ,
	'LBL_EXPORT_DATA_IN_CURRENT_PAGE' => 'Exportar dados na página atual',
	'LBL_EXPORT_SELECTED_RECORDS'=> 'Exportar Registros Selecionados' ,
	'LBL_EXPORT_RECORDS' => 'Exportar Registros',
	'LBL_NO_RECORD_SELECTED' => 'Nenhum registro selecionado.' ,
	'LBL_CAN_NOT_REMOVE_DEFAULT_WIDGET' => 'Não é possível remover widget padrão',
	'LBL_CUSTOM_VIEW_NAME_DUPLICATES_EXIST' => 'filtro já existente' ,

	'LBL_ADD_MANAGE_MODULES' => 'Adicionar/Administrar Módulos',
	
	// Added Common Keys for all modules
	'Account Name' => 'Nome Organização', 
	'Add Comment'=> 'Adicionar Comentário' ,
	'Adjustment' => 'Ajuste', 
	'Annual Revenue' => 'Receita Anual' , 
	'Apparel'=> 'Vestuário' ,
	'Banking'=> 'Bancos' ,
	'Billing Address'=> 'Endereço Faturamento' , 
	'Billing City' => 'Cidade Faturamento',
	'Billing Code' => 'CEP Faturamento',
	'Billing Country'=> 'País Faturamento' ,
	'Billing Po Box' => 'Cx Postal Faturamento',
	'Billing State'=> 'Estado Faturamento' ,
	'Biotechnology'=> 'Biotecnologia' ,

	//for SO PO and Quotes
	'FedEx'=> 'FedEx' ,
	'UPS'=> 'ECT' ,
	'USPS' => 'Braspress',
	'DHL'=> 'DHL' ,
	'BlueDart' => 'Cometa',
	'Carrier'=> 'Transportador' , 
	'Category' => 'Categoria' , 
	'Chemicals'=> 'Química' ,
	'City' => 'Cidade', 

	'Cold Call'=> 'Cold Call' ,
	'Existing Customer'=> 'Cliente Existente' ,
	'Self Generated' => 'Auto Gerado',
	'Employee' => 'Empregado',
	'Partner'=> 'Parceiro' ,
	'Public Relations' => 'Relações Públicas',
	'Direct Mail'=> 'Mala Direta' ,
	'Conference' => 'Conferência',
	'Trade Show' => 'Feira Negócios',
	'Web Site' => 'Web Site',
	'Word of mouth'=> 'Boca a Boca' ,
	'Other'=> 'Outro' ,

	//for leads and accounts
	'--None--' => '--Nada--',
	'Acquired' => 'Adquirido',
	'Active' => 'Ativo' , 
	'Market Failed'=> 'Perdido' ,
	'Project Cancelled'=> 'Projeto Cancelado' ,
	'Shutdown' => 'Encerrado',
	'Apparel'=>'Vestuário',
	'Banking'=>'Banco',
	'Biotechnology'=>'Biotecnologia',
	'Chemicals'=>'Química',
	'Communications' => 'Comunicações',
	'Construction' => 'Construção',
	'Consulting' => 'Consultoria',
	'Education'=> 'Educação' ,
	'Electronics'=> 'Eletrônicos' ,
	'Energy' => 'Energia',
	'Engineering'=> 'Engenharia' ,
	'Entertainment'=> 'Entretenimento' ,
	'Environmental'=> 'Meio Ambiente' ,
	'Finance'=> 'Finanças' ,
	'Food & Beverage'=> 'Alimentação & Bebidas' ,
	'Government' => 'Governo',
	'Healthcare' => 'Saúde',
	'Hospitality'=> 'Hotéis' ,
	'Insurance'=> 'Seguros' ,
	'Machinery'=> 'Maquinas' ,
	'Manufacturing'=> 'Indústria' ,
	'Media'=> 'Mídia' ,
	'Not For Profit' => 'ONG',
	'Recreation' => 'Recreação',
	'Retail' => 'Varejo',
	'Shipping' => 'Entrega',
	'Technology' => 'Tecnologia',
	'Telecommunications' => 'Telecomunicações',
	'Transportation' => 'Transportes',
	'Utilities'=> 'Serviço Público' ,

	'Contact Name' => 'Contato' , 
	'Conversion Rate'=> 'Taxa Câmbio' ,

	'Shipping Address' => 'Endereço Entrega' , 
	'Shipping City'=> 'Cidade Entrega' ,
	'Shipping State' => 'Estado Entrega',
	'Shipping Code'=> 'CEP Entrega',
	'Shipping Country' => 'País Entrega',
	'Shipping Po Box'=> 'Cx Postal Entrega' ,
	'Country'=> 'País' , 
	'Description' => 'Descrição',

	'Created'=> 'Criado',
	'Approved' => 'Aprovado',
	'Delivered'=> 'Entregue' ,
	'Cancelled'=> 'Cancelado' ,

	'Currency' => 'Moeda' ,
	'LBL_BASE_CURRENCY'=> 'Moeda Padrão',

	'Discount Percent' => 'Percentual Desconto',
	'Discount Amount'=> 'Valor Desconto' ,
	'Item Discount Amount' => 'Valor Desconto Item',
	'Item Discount Percent'=> 'Percentual Desconto Item' ,

	'Due Date' => 'Vencimento', 
	'Due Date & Time'=> 'Data & Hora Vencimento' ,
	'Email' => 'Email Principal',
	'Secondary Email' => 'Email Alternativo',
	'Other Email' => 'Outro Email',
	'Email Opt Out' => 'Recusa Email',
 
	'Expected Close Date'=> 'Previsão Fechamento', 

	'Fax'=> 'Fax' , 

	'Last Name'=> 'Sobrenome' , 
	'First Name' => 'Nome',

	'High' => 'Alto',
	'Low'=> 'Baixo' ,

	'In Progress'=> 'Em Andamento',


	'Subject'=> 'Assunto' ,
	'Shipping Address'=>'Endereço Entrega',
	'Shipping Po Box'=>'Cx Postal Entrega',
	'Shipping City'=>'Cidade Entrega',
	'Shipping State'=>'Estado Entrega',
	'Shipping Code'=>'CEP Entrega',
	'Shipping Country'=>'País Entrega',
	'Terms & Conditions' => 'Prazos & Condições', 
	'Item Name'=> 'Nome do Item',
	'Quantity' => 'Quantidade', 
	'List Price' => 'Lista de Preço' ,
	'Item Comment' => 'Comentário do Item',
	'Tax1' => 'Imposto1',
	'Tax2' => 'Imposto2',
	'Tax3' => 'Imposto3',
	'Excise Duty'=> 'IPI' , 
	'Total'=> 'Total' , 
	'Sub Total'=> 'Sub Total' ,
	'Tax Type' => 'Tipo Imposto',
	'S&H Amount' => 'Valor Frete',
	'Status' => 'Status', 
	'Vendor Name'=> 'Fornecedor',

	'LBL_ADDRESS_INFORMATION'=> 'Detalhes Endereço' ,
	'LBL_DESCRIPTION_INFORMATION'=> 'Descrição Detalhada' ,
	'LBL_TERMS_INFORMATION'=> 'Prazos & Condições',
	'LBL_PRICING_INFORMATION'=> 'Informação Preço Venda' ,
	'LBL_RELATED_PRODUCTS' => 'Detalhes do Produto' ,
	'LBL_REMINDER_INFORMATION' => 'Detalhes Lembrete',

	'LBL_FOLDER_SAVED' => 'Pasta salva',
	'LBL_FOLDER_EXISTS'=> 'Pasta já existente' ,
	'LBL_FOLDER_DELETED' => 'Pasta apagada',

	'Lead Source'=> 'Fonte Lead', 
	'Mobile' => 'Celular' ,
 
	'Notify Owner' => 'Notificar Proprietário' ,
	'Other Phone' => 'Telefone Alternativo',
	'Phone' => 'Telefone Principal',

	'State'=> 'Estado', 
	'Po Box' => 'Cx Postal',
	'Postal Code'=> 'CEP' ,

	'Potential Name' => 'Nome Oportunidade' , 
	'Priority' => 'Prioridade',

	'Product Name' => 'Nome Produto', 
	'Rating' => 'Avaliação' , 

	'Related To' => 'Relacionado à',
	'Type' => 'Tipo',
 
	'Reviewed' => 'Revisado',
	'Salutation' => 'Saudação', 
	'Street' => 'Rua' , 
	'Support Start Date' => 'Início Suporte' , 
	'Support Expiry Date'=> 'Data Final Suporte' ,
	'Sales Start Date' => 'Data Início Vendas',
	'Sales End Date' => 'Data Final Vendas',

	//Dashboard list of widgets translation
	'Open Ticktes' => 'Tickets Abertos',
	'LBL_SELECT_STATUS' => 'Selecionar Status',
	'LBL_BLANK' => '-Em branco-',

	//PageTitle translations
	'LBL_VTIGER_CRM_HONEST_OPEN_SOURCE' => 'vtiger CRM Open Source',

	//Translations used in inventory modules for sopy address
	'SINGLE_Accounts' => 'Organização',
	'SINGLE_Contacts' => 'Contato',

	//Weekdays in 3 letters translations
	'LBL_Sun' => 'Dom',
	'LBL_Mon' => 'Seg',
	'LBL_Tue' => 'Ter',
	'LBL_Wed' => 'Qua',
	'LBL_Thu' => 'Qui',
	'LBL_Fri' => 'Sex',
	'LBL_Sat' => 'Sab',

	//Months in 3 letters translations
	'LBL_Jan' => 'Jan',
	'LBL_Feb' => 'Fev',
	'LBL_Mar' => 'Mar',
	'LBL_Apr' => 'Abr',
	'LBL_May' => 'Mai',
	'LBL_Jun' => 'Jun',
	'LBL_Jul' => 'Jul',
	'LBL_Aug' => 'Ago',
	'LBL_Sep' => 'Set',
	'LBL_Oct' => 'Out',
	'LBL_Nov' => 'Nov',
	'LBL_Dec' => 'Dez',
	
	'LBL_CALENDAR_SETTINGS' => 'Configurações Agenda',
	
	//Translations used in inventory modules for sopy address
	'SINGLE_Accounts' => 'Organização',
	'SINGLE_Contacts' => 'Contato',
	'HelpDesk' => 'Tickets',
	'LBL_TAG_CLOUD' => 'Tag Cloud',

	'LBL_NO_RECORDS' => 'Nenhum Registro',
	'LBL_NO_RELATED' => 'Nenhum Relacionado',
	'LBL_GLOBAL_SEARCH_MAX_MESSAGE' => 'Somente os primeiros 100 resultados de todos os módulos serão exibidos abaixo. Para resultados específicos do módulo, por favor, selecione o respectivo módulo e pesquisa',
	'LBL_GLOBAL_SEARCH_MAX_MESSAGE_FOR_MODULE' => 'Somente os primeiros 100 resultados serão exibidos abaixo. Por favor, faça uma Pesquisa Avançada se você não está satisfeito com o resultado',

	// used in reports detail view
	'LBL ACTION' => 'Ação',
	'LBL_NOTE' => 'Nota',
	'LBL_SELECT_OPTION' => 'Selecionar uma Opção',

	//Module Manager
	'LBL_TOOLTIP' => 'Gestão Dicas de Contexto',
	'LBL_MODULE_SEQUENCE_NUMBERING' => 'Numeração Sequência Módulo',
	'LBL_CUSTOM_FIELD_MAPPING' => 'Mapeamento Campo Customizado',
	'LBL_WEBFORMS' => 'WebForms',
	
	//Compose Email Strings
	'SINGLE_Emails' => 'Email',
	'Emails' => 'Emails',
	'LBL_SELECT_EMAIL_IDS' => 'Selecionar Endereços de Email',
	'LBL_SUBJECT' => 'Assunto',
	'LBL_ATTACHMENT' => 'Anexo',
	'LBL_BROWSE_CRM' => 'Localizar CRM',
	'LBL_SEND' => 'Enviar',
	'LBL_SAVE_AS_DRAFT' => 'Salvar como Rascunho',
	'LBL_GO_TO_PREVIEW' => 'Ir para Visualização',
	'LBL_SELECT_EMAIL_TEMPLATE' => 'Selecionar Modelo Email',
	'LBL_COMPOSE_EMAIL' => 'Novo Email',
 	'LBL_CC' => 'Cc',
   	'LBL_BCC' => 'Bcc',
   	'LBL_ADD_CC' => 'Adicionar Cc',
   	'LBL_ADD_BCC' => 'Adicionar Bcc',
	'LBL_MAX_UPLOAD_SIZE' => 'Tamanho máximo de upload é',
	'LBL_EXCEEDED' => 'Excedido',
	'LBL_OPERATION_NOT_PERMITTED' => 'Operação não permitida',
    'LBL_MERGE' => 'Mesclar',
	'LBL_FIND_DUPLICATES' => 'Localizar Duplicados',
	'LBL_MERGING_CRITERIA_SELECTION' => 'Selecionar Critérios Mesclagem',
	'LBL_AVAILABLE_FIELDS' => 'Campos Disponíveis',
	'LBL_MERGE_RECORDS_DESCRIPTION' => 'O registro original será mantido após mesclagem. Você pode selecionar a coluna para manter o valor.
										O outro registro será excluído, mas a informação relacionada será mesclada.',
	'LBL_MERGE_RECORDS_IN' => 'Mesclar Registros em',
	'LBL_FIELDS' => 'Campos',
	'LBL_RECORD' => 'Registro',
	'LBL_NO_DUPLICATED_FOUND' => 'Nenhuma registro duplicado sof encontrado',
	'LBL_MERGE_SELECT' => 'Selecionar Mesclagem',

	//sbproducts translation
	'LBL_BACK_TO_PRODUCTS' => 'Voltar para produtos',
	
	//Translations used for Export to Pdf
	'Valid Date' => 'Data Validade',
	'Phone: ' => 'Telefone: ',
	'Issued Date' => 'Data Emissão',
	'Shipping & Handling Charges' => 'Frete',
	'Shipping & Handling Tax:' => 'Imposto Frete:',
	'Discount'=>'Desconto',
	'Net Total' => 'Total Líquido',
	'Product Code'=>'Código Produto',
	'Customer Name'=>'Nome Cliente',
	'Price'=>'Preço',
	'Tax:' => 'Imposto:',
	'Contact Name' => 'Nome Contato',
	'Grand Total:' => 'Total Geral:',
	'Fax: ' => 'Fax: ',
	'Website: ' => 'Website: ',
	'Tax' => 'Imposto',
	'LBL_ALPHABETS' => 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z',

	//Realted tab strings
	'Service Contracts' => 'Contratos Serviços',
	'Projects' => 'Projetos',
	'Sales Order' => 'Pedido Vendas',
	'Purchase Order' => 'Pedido Compras',
	'List and Campaigns' => 'Lista e Campanhas',
	'Project Tasks' => 'Tarefas Projeto',
	'Project Milestones' => 'Milestones Projeto',
		
	'Labels Editor' => 'Editor Rótulos',
	'LBL_IGNORE_EMPTY_VALUES' =>'Ignorar valores vazios',
		
	//Related tabs of Products
	'Product Bundles' => 'Produtos Compostos',
	'Parent Product' => 'Produto Pai',
	
	'LBL_MANAGE_USERS' => 'Gerenciar Usuários',
	'LBL_TRANSFER_OWNERSHIP' => 'Transferir Propriedade',
	'LBL_SELECT_RELATED_MODULES' => 'Selecionar Módulos Relacionados',
	'LBL_ASSIGNED_TO' => 'Designado a',
		
	//Report Detail View
	'LBL_VIEW_DETAILS' => 'Visualizar Datalhes',

//Missing fields
	'PickListDependency'=>'Dependência Lista Opções',
	'Users'=>'Usuários',
	'SMSNotifier'=>'Notificador SMS',
	'Key Metrics'=>'Métricas Chave',
	'Recicle Bin'=>'Lixeira',
	'generalFields' => 'Outros Campos',
	'Service No'=>'Cod. Serviço',
	'Service Name'=>'Nome Serviço',
	'Price'=>'Preço',
	'Usage Unit'=>'Unidade Utilizada',
	'Service Active'=>'Serviço Ativo',
	'No of Units'=>'No. Unidades',
	'Service Category'=>'Categoria Serviço',
	'Owner'=>'Proprietário',
	'Commission Rate'=>'Percentual Comissão',
	'Tax Class'=>'Categoria Imposto',
);

$jsLanguageStrings = array(
	'JS_EMAIL_SERVER_CONFIGURATION' => 'Por favor, ajuste as configurações do Servidor Envio Mensagens a partir do menu Configurações',
	'JS_SMS_SERVER_CONFIGURATION'=> 'Por favor, configure seu Notificador SMS na página de configuração do Notificar SMS',
	'JS_PLEASE_SELECT_ONE_RECORD'=> 'Por favor, selecione ao menos um registro',

	//Validation Error Message
	'JS_PLEASE_ENTER_VALID_EMAIL_ADDRESS' => 'Por favor, digite um endereço de email válido',
	'JS_CONTAINS_ILLEGAL_CHARACTERS' => 'contém caracteres não permitidos' ,
	'JS_PHONE_NUMBER_LENGTH_EXCEEDED' => 'comprimento do número de telefone excedeu o limite',
	'JS_ACCEPT_POSITIVE_NUMBER'=> 'aceita somente valores positivos',
	'JS_VALUE_SHOULD_BE_GREATER_THAN_ZERO' => 'o valor deve ser maior que zero',
	'JS_NUMBER_SHOULD_BE_LESS_THAN_32' => 'O número deve ser menor que 32',
	'JS_PLEASE_ENTER_VALID_DATE' => 'Por favor, digite uma data válida',
	'JS_PLEASE_ENTER_VALID_TIME' => 'Por favor, digite uma hora válida',
	'JS_INVALID_PAGE_NUMBER' => 'Número de Página Inválido',


	'INVALID_NUMBER_OF'=> 'Número inválido de',
	'INVALID_NUMBER' => 'Número inválido',
	'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE' => 'Tem certeza que deseja apagar?',

	'OVERWRITE_EXISTING_MSG1'=> 'Sobrescrever o endereço existente pelo endereço selecionado? ',
	'OVERWRITE_EXISTING_MSG2'=> 'Detalhes do Endereço' ,
	'SINGLE_Accounts'=> 'Organização',
	'SINGLE_Contacts'=> 'Contato' ,

	'LBL_DELETE_CONFIRMATION'=> 'Tem certeza que deseja Apagar?', // This is added as duplicate as we need to show different message for different modules. Ex:Accounts has different message
	'LBL_MASS_DELETE_CONFIRMATION' => 'Tem certeza que deseja apagar os Registros selecionados?',
	'JS_LBL_SAVE'=> 'Salvar',
	'JS_LBL_CANCEL'=> 'Cancelar',
	'JS_DUPLICTAE_CREATION_CONFIRMATION' => 'O nome da Organização já existe. Deseja criar um registro duplicado?',

	'SHOULD_BE_LESS_THAN_TODAY'=> 'Deve ocorrer antes de hoje' ,
	'JS_PLEASE_SELECT_ATLEAST_ONE_OPTION' => 'Por favor, selecione ao menos uma opção',
	'JS_SELECT_MODULE' => 'Por favor, selecione o Módulo',
	'JS_PLEASE_SELECT_ATLEAST_ONE_MANDATORY_FIELD' => 'Por favor, selecione ao menos um Campo Obrigatório',
	'JS_SELECT_MODULE' => 'Por favor, selecione um Módulo',
	'JS_PLEASE_ENTER_INTEGER_VALUE' => 'Por favor, digite um valor inteiro',
	'JS_PLEASE_ENTER_DECIMAL_VALUE' => 'Por favor, digite um valor decimal',

	'JS_SHOULD_BE_LESS_THAN_CURRENT_DATE' => 'deve ser menor que a Data Atual',
	'JS_SHOULD_BE_GREATER_THAN_CURRENT_DATE' => 'deve ser maior que a Data Atual',
	'JS_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO' => 'deve ser maior ou igual a',
    'JS_SHOULD_BE_LESS_THAN_OR_EQUAL_TO' => 'deve ser menor que ou igual a',
	'JS_PERCENTAGE_VALUE_SHOULD_BE_LESS_THAN_100' => 'O valor percentual deve ser menor que 100',
	'JS_ACCEPT_ONLY_NUMBER' => 'Aceita somente números',
	'JS_THIS_FILE_HAS_ALREADY_BEEN_SELECTED' => 'Este arquivo já foi selecionado',
	'JS_MAX_FILE_UPLOAD_EXCEEDS' => 'Transferência máxima de arquivo excedeu',
	'JS_THIS_DOCUMENT_HAS_ALREADY_BEEN_SELECTED' => 'Este Documento já foi anexado',
	'JS_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO' => 'Deve ser maior ou igual a',


	//Roles
	'JS_FAILED_TO_SAVE'=> 'Falha ao salvar as mudanças no Servidor',

	//Import Translations
	'JS_IMPORT_FILE_CAN_NOT_BE_EMPTY' => 'O Arquivo a ser Importado não pode estar Vazio' ,
	'JS_PLEASE_SELECT_ONE_FIELD_FOR_MERGE' => 'Selecionar ao menos um campo para definir o critério para mesclagem',
	'JS_MAP_NAME_CAN_NOT_BE_EMPTY' => 'O Nome do Mapa não pode estar vazio',
	'JS_MAP_NAME_ALREADY_EXISTS' => 'Nome do Mapa já existente' ,
	'JS_SELECT_FILE_EXTENSION' => 'Por favor, selecione um arquivo com a seguinte extensão:',
	'JS_UPLOADED_FILE_SIZE_SHOULD_BE_LESS_THAN' => 'O tamanho do arquivo deve ser inferior a',
	'JS_UPLOADED_FILE_SIZE_EXCEEDS' => 'Tamanho do arquivo excedeu',
	'JS_PLEASE_SPLIT_FILE_AND_IMPORT_AGAIN' => 'Por favor, divida o arquivo em arquivos menores e importe novamente.',
	'JS_FIELD_MAPPED_MORE_THAN_ONCE' => 'Campo mapeado mais de um vez' ,
	'JS_MAP_MANDATORY_FIELDS'=> 'Por favor, mapear campos obrigatórios' ,
	'JS_PLEASE_ENTER_SOME_VALUE' => 'Por favor, digite ao menos um valor para pesquisa',

	//Select2 elements validation message
	'JS_YOU_CAN_SELECT_ONLY' => 'Você deve selecionar somente' ,
	'JS_ITEMS' => 'itens' ,

	'JS_LBL_PERMISSION'=> 'Permissões' ,
	'JS_CHECK_FILE_INTEGRITY'=> 'Checar Integridade do Arquivo',
	'JS_DUPLICATE_RECORD'=> 'Registro Duplicado',

	//advance filter checkbox type condition values
	'JS_IS_ENABLED'=> 'está habilitado',
	'JS_IS_DISABLED' => 'está desabilitado' ,

	'JS_PLEASE_ENTER_SOME_TEXT_FOR_COMMENT' => 'Por favor, digite algum texto para Comentário',
	'JS_LBL_COMMENT_VALUE_CANT_BE_EMPTY' => 'O valor do Comentário não pode estar vazio',
	'JS_REQUIRED_FIELD'=> '* Este campo é obrigatório',
	'JS_CAN_NOT_REMOVE_DEFAULT_WIDGET' => 'Não é possível remover o Widget Padrão',
	'JS_SHOULD_BE_LESS_THAN_CURRENT_DATE' => 'deve ser menor que a Data Atual',
	'JS_NO_CREATE_OR_NOT_QUICK_CREATE_ENABLED' => 'Nenhuma permissão criada ou não está habilitado para Criar Rápido',

	//Image Action
	'LBL_IMAGE_DELETED_SUCCESSFULLY' => 'A imagem foi apagada com Sucesso',
	'LBL_IMAGE_NOT_DELETED'=> 'A imagem não foi Apagada' ,
	'LBL_YES'=> 'Sim' ,
	'LBL_NO' => 'Não',
	'AM' => 'AM',
	'PM' => 'PM',
 	'JS_ERROR' => 'Erro',
	'JS_INFORMATION' => 'Informação',
	'JS_DO_NOT_HAVE_AN_EMAIL_ID' => 'não existe um endereço de email',
	'NONE_OF_THE_FIELD_VALUES_ARE_CHANGED_IN_MASS_EDIT' => 'Nenhum dos valores de campos são alterados na Edição em Massa',
	
	//Notification messages for inventory module
	'JS_PLEASE_SELECT_AN_ACCOUNT_TO_COPY_ADDRESS' => 'Por favor, selecione uma Organização para copiar o endereço',
	'JS_PLEASE_SELECT_AN_CONTACT_TO_COPY_ADDRESS' => 'Por favor, selecione um Contato para copiar o endereço',
	'JS_SELECTED_ACCOUNT_DOES_NOT_HAVE_AN_ADDRESS' => 'A Organização selecionada não possui um endereço para copiar',
	'JS_SELECTED_CONTACT_DOES_NOT_HAVE_AN_ADDRESS' => 'O Contato selecionado não possui um endereço para copiar',
	'JS_PLEASE_ENTER_PRIMARY_EMAIL_VALUE_TO_ENABLE_PORTAL_USER' => 'Por favor, digite o email principal para habilitar o acesso do Usuário do Portal',
	'JS_PRIMARY_EMAIL_FIELD_DOES_NOT_EXISTS' => 'Falta o email principal para habilitar acesso do Usuário ao Portal',
	
	//Tag Cloud validation messages
	'JS_PLEASE_ENTER_A_TAG' => 'Por favor, digite uma etiqueta',
	'JS_TAG_NAME_ALREADY_EXIST' => 'O nome da etiqueta já existe',
	'JS_MAX_TAG_LENGTH_EXCEEDS' => 'O comprimento da etiqueta excedeu o tamanho máximo',
	
	'JS_NO_VIEW_PERMISSION_AFTER_SAVE'=> 'Você não terá permissão para visualizar estes recurso depois que salvar. Deseja continuar?',
	'JS_NO_RECORDS_RELATED_TO_THIS_FILTER' => 'Nenhum Registro Relacionado para este Filtro',

	// Calendar Reminder popup
	'JS_START_DATE_TIME' => 'Data & Hora Início',
	'JS_END_DATE_TIME' => 'Data & Hora Final',
	'JS_POSTPONE' => 'Adiar',
	'JS_MESSAGE' => 'Mensagem',
	
	'JS_NO_VIEW_PERMISSION_AFTER_SAVE'=> 'Após salvar você não terá permissão para visualizar este registro. Deseja continuar?',
	
	//Settings page translations
	'JS_SUCCESSFULLY_PINNED' => 'Atalho adicionado com sucesso',
	'JS_SUCCESSFULLY_UNPINNED' => 'Atalho removido com sucesso',
	'JS_SHORTCUT_ALREADY_ADDED' => 'Este atalho já foi adicionado',
	'JS_MESSAGE' => 'Mensagem',
	
	//Module Manager
	'JS_MODULE_ENABLED' => 'Módulo Habilitado',
	'JS_MODULE_DISABLED' => 'Módulo Desabilitado',
	
	//Crom tasks
	'JS_VALUE_SHOULD_NOT_BE_LESS_THAN' => 'A frequência de qualquer tarefa configurada no Cron não deve ser inferior a',
	'JS_MINUTES' => 'min',
	
	//PickList 
	'JS_ITEM_RENAMED_SUCCESSFULLY' => 'Item Renomeado com Sucesso',
	'JS_ITEM_ADDED_SUCCESSFULLY' => 'Item adicionado com Sucesso',
	'JS_NO_ITEM_SELECTED' => 'Nenhum item Selecionado',
	'JS_MORE_THAN_ONE_ITEM_SELECTED' => 'Mais de um Item selecionado',
	'JS_ITEMS_DELETED_SUCCESSFULLY' => 'Itens Apagados com sucesso',
	'JS_DUPLIACATE_ENTRIES_FOUND_FOR_THE_VALUE' => 'Foi encontrado valor duplicado',
	'JS_SELECT_RECORDS_TO_MERGE_FROM_SAME_GROUP' => 'Voce deve selecionar os registros nos mesmos grupos para mesclar',
	'JS_SELECT_ATLEAST_TWO_RECORD_FOR_MERGING' => 'Selecionar pelo menos dois registros para mesclar',
	'JS_ALLOWED_TO_SELECT_MAX_OF_THREE_RECORDS' => 'Você tem permissão para selecionar no máximo três registros',
	//Notification message for dashboard widget delete
	'JS_ARE_YOU_SURE_TO_DELETE_WIDGET' => 'Tem certeza que deseja excluir o widget',
	'JS_DUPLICATE_ENTRIES_FOUND_FOR_THE_VALUE' => 'Duplicar entradas encontrada para o valor',
	'JS_SELECT_RECORDS_TO_MERGE_FROM_SAME_GROUP' => 'Você tem que selecionar os registros nos mesmos grupos para mesclar',
	'JS_SELECT_ATLEAST_TWO_RECORD_FOR_MERGING' => 'Selecionar ao menos dois registros para mesclar',
	'JS_ALLOWED_TO_SELECT_MAX_OF_THREE_RECORDS' => 'Você tem permissão para selecionar no máximo três registros',
	'JS_TOTAL_RECORDS' => 'Total registros',
	'JS_PAGE_NOT_EXIST' => 'A página não existe',
	'JS_YOU_ARE_IN_PAGE_NUMBER' => 'Você está na página número',
	
	//More currencies message
	'JS_PLEASE_ENABLE_BASE_CURRENCY_FOR_PRODUCT' => 'Por favor, habilite a moeda padrão para o produto',
	'JS_PLEASE_SELECT_BASE_CURRENCY_FOR_PRODUCT' => 'Por favor, selecione a moeda padrão para o produto',
		
	//Delete Records message
	'JS_RECORDS_ARE_GETTING_DELETED' => 'Os registros estão sendo excluídos',
	'JS_RECORD_GETTING_DELETED' => 'Registros sendo apagados',
	'JS_NO_RESULTS_FOUND' => 'Nenhum resultado encontrado',
	
	'JS_RECORDS TRANSFERRED SUCCESSFULLY' => 'Os registros do proprietário foram transferidos com sucesso',
	
	'JS_USER_EXISTS' => 'O Usuário já Existe',
	'JS_REENTER_PASSWORDS' => 'Redigite a Senha',
);