<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger. All Rights Reserved.
 * Contributor(s): Valmir C. Trindade - Translate to Brazilian Portuguese - 14/07/2013 - www.ttcasolucoes.com.br
 *************************************************************************************/
$languageStrings = array(
	'LayoutEditor' => 'Editor de Layout',
	'LBL_FIELDS_AND_LAYOUT_EDITOR' => 'Editor de Campos e Layout',
	'LBL_CREATE_CUSTOM_FIELD' => 'Criar Campo Customizado',
	'LBL_DETAILVIEW_LAYOUT' => 'Layout Detalhes Visualização',
	'LBL_ARRANGE_RELATED_TABS' => 'Organizar Abas Relacionadas',
	'LBL_ADD_CUSTOM_FIELD' => 'Adicionar Campo Customizado',
	'LBL_ADD_CUSTOM_BLOCK' => 'Adicionar Bloco Customizado',
	'LBL_SAVE_FIELD_SEQUENCE' => 'Salvar Sequência Campo',
	'LBL_BLOCK_NAME' => 'Nome Bloco',
	'LBL_ADD_AFTER' => 'Adicionar Depois',
	'LBL_ACTIONS' => 'Ações',
	'LBL_ALWAYS_SHOW' => 'Exibir Sempre',
	'LBL_INACTIVE_FIELDS' => 'Campos Inativos',
	'LBL_DELETE_CUSTOM_BLOCK' => 'Apagar Bloco Customizado',
	'LBL_MANDATORY_FIELD' => 'Campo Obrigatório',
	'LBL_ACTIVE' => 'Ativo',
	'LBL_QUICK_CREATE' => 'Criar Rápido',
	'LBL_SUMMARY_FIELD' => 'Visualizar Resumo',
	'LBL_MASS_EDIT' => 'Editar em Massa',
	'LBL_DEFAULT_VALUE' => 'Valor Padrão',
	'LBL_SELECT_FIELD_TYPE' => 'Seleciconar Tipo Campo',
	'LBL_LABEL_NAME' => 'Nome Rótulo',
	'LBL_LENGTH' => 'Comprimento',
	'LBL_DECIMALS' => 'Decimais',
	'LBL_ENTER_PICKLIST_VALUES' => 'Digite Valores da Lista Opções..',
	'LBL_PICKLIST_VALUES' => 'Valor Lista Opções',
	'LBL_INACTIVE_FIELDS' => 'Campos Inativos',
	'LBL_REACTIVATE' => 'Reativar',
	'LBL_ARRANGE_RELATED_LIST' => 'Organizar Lista Relacionada',
	'LBL_SELECT_MODULE_TO_ADD' => 'Selecionar Módulo para Adicionar',
	'LBL_NO_RELATED_INFORMATION' => 'Nenhuma Informação Relacionada',
	'LBL_RELATED_LIST_INFO' => 'Arraste e solte o módulo para reordenar a lista',
	'LBL_REMOVE_INFO' => 'Clique sobre o ícone "fechar" para remover o módulo da lista',
	'LBL_ADD_MODULE_INFO' => 'Selecionar o móduo removido para adiciona-lo de volta para a lista',
	'LBL_SELECT_MODULE' => 'Selecionar Módulo..',
	'LBL_DUPLICATES_EXIST' => 'Nome do Bloco já existe',
	'LBL_NON_ROLE_BASED_PICKLIST' => 'Nenhuma Lista de Opções Baseada em Função',
	'LBL_DUPLICATE_FIELD_EXISTS' => 'Duplicar Campo Existente',
	'LBL_WRONG_FIELD_TYPE' => 'Tipo de Campo Errado',
	'LBL_ROLE_BASED_PICKLIST' => 'Lista de Opções Baseada em Função',

	//Field Types
	'Text'=>'Texto',
	'Decimal'=>'Decimal',
	'Integer'=>'Número',
	'Percent'=>'Percentual',
	'Currency'=>'Moeda',
	'Date'=>'Data',
	'Email'=>'Email',
	'Phone'=>'Telefone',
	'PickList'=>'Lista Opções',
	'MultiSelectCombo'=>'Caixa Múltipla Seleção',
	'URL' => 'URL',
	'Checkbox' => 'Caixa Seleção',
	'TextArea' => 'Área de Texto',
	'Skype'=>'Skype',
	'Time'=>'Hora',
);

$jsLanguageStrings = array(
	'JS_BLOCK_VISIBILITY_SHOW' => 'Exibir Bloco habilitado',
	'JS_BLOCK_VISIBILITY_HIDE' => 'Ocultar Bloco habilitado',
	'JS_CUSTOM_BLOCK_ADDED' => 'Novo Bloco Customizado adicionado',
	'JS_BLOCK_SEQUENCE_UPDATED' => 'Sequência Blocos Atualizada',
	'JS_SELECTED_FIELDS_REACTIVATED' => 'Campos Selecionados Reativados',
	'JS_FIELD_DETAILS_SAVED' => 'Detalhes do Campo Salvo',
	'JS_CUSTOM_BLOCK_DELETED' => 'Bloco Customizado Apagado',
	'JS_CUSTOM_FIELD_ADDED' => 'Novo Campo Customizado Adicionado',
	'JS_CUSTOM_FIELD_DELETED' => 'Campo Customizado Apagado',
	'JS_LENGTH_SHOULD_BE_LESS_THAN_EQUAL_TO' => 'O comprimento deve ser menor ou igual a',
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE_2TO5' => 'Decimal deve estar no intervalo de 2 a 5',
	'JS_SAVE_THE_CHANGES_TO_UPDATE_FIELD_SEQUENCE' => 'Salvar as mudanças para atualizar a sequência de Campos',
	'JS_RELATED_INFO_SAVED' => 'Informação Relacionada Salva',
	'JS_BLOCK_NAME_EXISTS' => 'Nome do Bloco já existe',
	'JS_NO_HIDDEN_FIELDS_EXISTS' => 'Nenhum Campo Inativo',
	'JS_SPECIAL_CHARACTERS' => 'Caracteres Especiais como',
	'JS_NOT_ALLOWED' => 'não são permitidos',
	'JS_FIELD_SEQUENCE_UPDATED' => 'Sequência de Campos Atualizada',
	'JS_DUPLICATES_VALUES_FOUND' => 'Foram encontrados Valores Duplicados'
);
